name: Automatic Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Project [adc.ms.eureka]
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        id: git_checkout
        uses: actions/checkout@v1
        env:
          commit_id: 113wqeqweq

      - name: Set up JDK 12.0
        uses: actions/setup-java@v1
        with:
          java-version: 12.0

      - name: Build with Gradle
        run: gradle build

      - name: Docker Images Build And Push To Hub
        id: build_push_image
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: 'useccr.ccs.tencentyun.com'
          namespaces: 'adc.ms.usa'
          repository_name: 'adc.ms.eureka'
          user_name: ${{ secrets.TENCENT_IMAGES_HUB_USER_NAME }}
          password: ${{ secrets.TENCENT_IMAGES_HUB_TOKEN }}
          image_version: ${{ github.sha }}
          docker_file: '.'

      - name: Get pre step result output image_pull_url
        if: success()
        run: echo "image_pull_url=${{ steps.build_push_image.outputs.image_pull_url }}" \
          && echo "env commit_id=${{ steps.env.commit_id }}"








