name: Automatic Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout Code
      uses: actions/checkout@v1

    - name: Set up JDK 12.0
      uses: actions/setup-java@v1
      with:
        java-version: 12.0

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker Image
      run: echo "All Process OK!!"

