name: Automatic Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1

      - name: Set Up JDK 12.0
        uses: actions/setup-java@v1
        with:
          java-version: 12.0

      - name: Build With Gradle
        run: gradle build

      - name: Docker Images Build And Push To Hub
        id: build_push_image
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: ${{ secrets.TENCENT_IMAGES_HUB_REGISTRY_URL }}
          namespaces: ${{ secrets.TENCENT_IMAGES_HUB_NAMESPACES }}
          repository_name: ${{ secrets.TENCENT_IMAGES_HUB_REPOSITORY_NAME }}
          user_name: ${{ secrets.TENCENT_IMAGES_HUB_USER_NAME }}
          password: ${{ secrets.TENCENT_IMAGES_HUB_TOKEN }}
          image_version: ${{ github.sha }}
          docker_file: '.'

      - name: Create Docker Run Script
        run: echo ::set-env name=APP_RUN_DOCKER_SCRIPT::"\
        echo ${{ secrets.TENCENT_IMAGES_HUB_TOKEN }} | \
        docker login --username=${{ secrets.TENCENT_IMAGES_HUB_USER_NAME }} \
        ${{ secrets.TENCENT_IMAGES_HUB_REGISTRY_URL }} --password-stdin && \
        docker run -p 8080:80 -d ${{ steps.build_push_image.outputs.image_pull_url }}"

      - name: Remote Server Exce Run Shell Commands
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.HOSTWINDS_SERVER_CENTOS_HOST_IP }}
          username: ${{ secrets.HOSTWINDS_SERVER_CENTOS_USERNAME }}
          key: ${{ secrets.REMOTE_SERVER_ID_RSA_PRIVATE_KEY }}
          port: ${{ secrets.HOSTWINDS_SERVER_CENTOS_PORT }}
          script: ${{ env.APP_RUN_DOCKER_SCRIPT }}







