name: Automatic Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1

      - name: Set Up JDK 12.0
        uses: actions/setup-java@v1
        with:
          java-version: 12.0

      - name: Build With Gradle
        run: gradle build

      - name: Docker Images Build And Push To Hub
        id: build_push_image
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: ${{ secrets.TENCENT_IMAGES_HUB_REGISTRY_URL }}
          namespaces: ${{ secrets.TENCENT_IMAGES_HUB_NAMESPACES }}
          repository_name: ${{ secrets.TENCENT_IMAGES_HUB_REPOSITORY_NAME }}
          user_name: ${{ secrets.TENCENT_IMAGES_HUB_USER_NAME }}
          password: ${{ secrets.TENCENT_IMAGES_HUB_TOKEN }}
          image_version: ${{ github.sha }}
          docker_file: '.'

      - name: Generate Docker Start Script
        env:
          DOCKER_RUN_CONTAINER_NAME: adc.ms.eureka
          DOCKER_IMAGES_REGISTRY_NAME: ${{ secrets.TENCENT_IMAGES_HUB_REGISTRY_URL }}/${{ secrets.TENCENT_IMAGES_HUB_NAMESPACES }}/${{ secrets.TENCENT_IMAGES_HUB_REPOSITORY_NAME }}
        run: |
          echo ::set-env name=DOCKER_LOGIN_SCRIPT::"echo ${{ secrets.TENCENT_IMAGES_HUB_TOKEN }} | docker login --username=${{ secrets.TENCENT_IMAGES_HUB_USER_NAME }} ${{ secrets.TENCENT_IMAGES_HUB_REGISTRY_URL }} --password-stdin"
          echo ::set-env name=DOCKER_CONTAINER_STOP_SCRIPT::"docker stop ${{ env.DOCKER_RUN_CONTAINER_NAME }}"
          echo ::set-env name=DOCKER_CONTAINER_REMOVE_SCRIPT::"docker rm ${{ env.DOCKER_RUN_CONTAINER_NAME }}"
          echo ::set-env name=DOCKER_IMAGES_REMOVE_SCRIPT::"docker rmi (docker images | grep ${{ env.DOCKER_IMAGES_REGISTRY_NAME }} | awk '{print $3}')"
          echo ::set-env name=DOCKER_CONTAINER_RUN_SCRIPT::"docker run -d --name ${{ env.DOCKER_RUN_CONTAINER_NAME }} ${{ steps.build_push_image.outputs.image_pull_url }}"



      - name: Remote Server Exce Run Shell Commands
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.TENCENT_SERVER_CENTOS_HOST_IP }}
          username: ${{ secrets.HOSTWINDS_SERVER_CENTOS_USERNAME }}
          key: ${{ secrets.REMOTE_SERVER_ID_RSA_PRIVATE_KEY }}
          port: ${{ secrets.HOSTWINDS_SERVER_CENTOS_PORT }}
          script: |
            ${{ env.DOCKER_LOGIN_SCRIPT }}
            ${{ env.DOCKER_CONTAINER_STOP_SCRIPT }}
            ${{ env.DOCKER_CONTAINER_REMOVE_SCRIPT }}
            ${{ env.DOCKER_IMAGES_REMOVE_SCRIPT }}
            ${{ env.DOCKER_CONTAINER_RUN_SCRIPT }}







