name: Automatic Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout
        env:
          commit_id: 113wqeqweq

      - name: Set up JDK 12.0
        uses: actions/setup-java@v1
        with:
          java-version: 12.0

      - name: Build with Gradle
        run: ./gradlew build

      - name: Aliyun Docker Images Build And Push
        uses: risfeng/aliyun-docker-image-build-push-action@v0.7
        with:
          registry_url: registry.us-east-1.aliyuncs.com
          namespaces: adotcode
          repository_name: adc.ms.eureka.usa
          user_name: ${{ secrets.ALIYUN_IMAGES_HUB_USER_NAME }}
          password: ${{ secrets.ALIYUN_IMAGES_HUB_TOKEN }}
          image_name: adc.ms.eureka.usa
          image_version: v1.2
          docker_file: .







